### ISSUE TITLE
I can't use any of the search results

### ISSUE THREAD

**Issue by krux02** [rasguanabana/ytfs#27]
This is my error message when I try to copy it, (in english it would be "can't open for reading, invalid address")

```
cp Rick\ Astley\ -\ Never\ Gonna\ Give\ You\ Up\ \[HQ\].mp4 ..
cp: 'Rick Astley - Never Gonna Give You Up [HQ].mp4' kann nicht zum Lesen geöffnet werden: Ungültige Adresse
```

Also playing with mplayer doesn't work.

I am runnig on Arch Linux.

**Comment by rasguanabana** [comment]
Hi, please mount ytfs with -d option and provide error message. This probably will be fixed with a next commit, but anyway more info might be useful.

**Comment by krux02** [comment]
```
$ ytfs -d youtube                                      
Mounting YTFS ver. 0.99a4.
If you encounter any bugs, please open an issue on GitHub: https://github.com/rasguanabana/ytfs
Traceback (most recent call last):
  File "/home/arne/.local/lib/python3.6/site-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/home/arne/.local/lib/python3.6/site-packages/fuse.py", line 572, in open
    fi.flags)
  File "/home/arne/.local/lib/python3.6/site-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "/home/arne/.local/lib/python3.6/site-packages/ytfs/ytfs.py", line 323, in mod
    return method(self, self.__pathToTuple(path), *args)
  File "/home/arne/.local/lib/python3.6/site-packages/ytfs/ytfs.py", line 565, in open
    if yts.obtainInfo(): #FIXME coz it's ugly.
  File "/home/arne/.local/lib/python3.6/site-packages/ytfs/stor.py", line 234, in obtainInfo
    if self.preferences['audio'] and self.preferences['video']: fm = sorted(full, key=_k)
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by rasguanabana** [comment]
I have just updated PyPI package, please do `pip install --upgrade ytfs` and try again.

**Comment by krux02** [comment]
Well, this works now.
