### ISSUE TITLE
Network is down

### ISSUE THREAD

**Issue by abhi204** [rasguanabana/ytfs#30]
cannot open file.mp4 for reading: **Network is down**

**Comment by rasguanabana** [comment]
Hi, does this issue reoccur? If yes, please run ytfs in debug mode (`ytfs -d`) and copy traceback when the error happens

**Comment by abhi204** [comment]
Yes, the issue recurring.
here is the log:

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1199, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1110, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1171, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 971, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
